### PR TITLE
add region discovery

### PR DESCRIPTION
**Pull request by ro0NL**
https://jsfiddle.net/bzdjke6m/1/

### CODE REVIEW

**Comment by yceruto** [comment]
It seems a bit messy (discover):
discover

**Comment by yceruto** [comment]
I'd not add that option (discover) ;)

**Comment by ro0NL** [comment]
well those are the actual regions, this is the only way you can discover them live.

WDYT of https://jsfiddle.net/bzdjke6m/2/ ?

**Comment by ro0NL** [comment]
i like this one :) https://jsfiddle.net/bzdjke6m/6

**Review by yceruto — APPROVED** [review]
much better!

**Comment by yceruto** [comment]
what about "undiscover" action? discover/undiscover

**Comment by ro0NL** [comment]
done https://jsfiddle.net/bzdjke6m/9/

**Review by yceruto — APPROVED** [review]
perfect!

**Pull request merged**
